development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_test_development 
  pool: 5
  username: <%= ENV['RAILS_TEST_APP_MYSQL_USERNAME'] %>
  password: <%= ENV['RAILS_TEST_APP_MYSQL_PASSWORD'] %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_test_test
  pool: 5
  username: <%= ENV['RAILS_TEST_APP_MYSQL_USERNAME'] %>
  password: <%= ENV['RAILS_TEST_APP_MYSQL_PASSWORD'] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_test_production
  pool: 5
  username: <%= ENV['RAILS_TEST_APP_MYSQL_USERNAME'] %>
  password: <%= ENV['RAILS_TEST_APP_MYSQL_PASSWORD'] %>
